previous_run_path: models/RENIVariationalAutoDecoder/network_128_5/ndims_36/
dataset_path: data/processed/HDRI_Train/
test_dataset_path: data/processed/HDRI_Test/
latent_code_optimisation: True
inverse_rendering_task: False
multi_res_training: True
resize_transform_start: 32
resize_transform_end: 128
epochs: 2400
epochs_till_res_change: 800
epochs_till_images: 50
epochs_till_checkpoint: 200
kld_weighting: 0.0001
lr_train_start: 0.00001
lr_train_end: 0.0000001
lr_schedule: exponential
train_batch_size: 1
model_type: RENIVariationalAutoDecoder
ndims: 36
RENI_hidden_layers: 5
RENI_hidden_features: 128
last_layer_linear: True
optimizer: adam