wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1652164545
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.12
      5: 0.12.16
      8:
      - 5
apply_mask:
  desc: null
  value: true
batch_size:
  desc: null
  value: 1
dataset_path:
  desc: null
  value: data/processed/HDRI_Dataset_128_Train/
epochs:
  desc: null
  value: 2400
epochs_latent:
  desc: null
  value: 2400
epochs_till_checkpoint:
  desc: null
  value: 200
epochs_till_images:
  desc: null
  value: 50
epochs_till_res_change:
  desc: null
  value: 800
equivariance:
  desc: null
  value: SO2
inverse_cosine_similarity_weight:
  desc: null
  value: 1000
inverse_prior_loss_weight:
  desc: null
  value: 0.0001
inverse_rendering_task:
  desc: null
  value: false
kd_value:
  desc: null
  value: 1.0
kld_weighting:
  desc: null
  value: 0.0001
latent_code_optimisation:
  desc: null
  value: true
latent_cosine_similarity_weight:
  desc: null
  value: 0.1
latent_epochs_till_res_change:
  desc: null
  value: 800
latent_image_size:
  desc: null
  value: 64
latent_multi_res_training:
  desc: null
  value: true
latent_prior_loss_weight:
  desc: null
  value: 1.0e-07
latent_resize_transform_end:
  desc: null
  value: 128
latent_resize_transform_start:
  desc: null
  value: 32
lr_latent_end:
  desc: null
  value: 0.0001
lr_latent_schedule:
  desc: null
  value: exponential
lr_latent_start:
  desc: null
  value: 0.01
lr_schedule:
  desc: null
  value: exponential
lr_train_end:
  desc: null
  value: 1.0e-08
lr_train_start:
  desc: null
  value: 1.0e-06
mask_path:
  desc: null
  value: data/processed/Masks/Mask-3.png
model_type:
  desc: null
  value: RENIVariationalAutoDecoder
multi_gpu:
  desc: null
  value: true
multi_res_training:
  desc: null
  value: false
ndims:
  desc: null
  value: 20
object_path:
  desc: null
  value: data/graphics/3d_models/teapot.obj
optimizer:
  desc: null
  value: adam
previous_run_path:
  desc: null
  value: models/RENIVariationalAutoDecoder/network_128_5/ndims_36/
render_resolution:
  desc: null
  value: 128
resize_transform_end:
  desc: null
  value: 64
resize_transform_start:
  desc: null
  value: 32
RENI_hidden_features:
  desc: null
  value: 128
RENI_hidden_layers:
  desc: null
  value: 5
test_dataset_path:
  desc: null
  value: data/processed/HDRI_Test/
trained_on_LDR:
  desc: null
  value: false
last_layer_linear:
  desc: null
  value: false